# Generated by Django 5.2.8 on 2025-12-31 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_subscriber_alter_notice_id_alter_photo_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriber',
            options={'ordering': ['-subscribed_at'], 'verbose_name_plural': 'Subscribers'},
        ),
        migrations.RenameField(
            model_name='subscriber',
            old_name='created_at',
            new_name='subscribed_at',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='token',
        ),
        migrations.AddField(
            model_name='subscriber',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='name',
            field=models.CharField(default='Unknown', max_length=200),
            preserve_default=False,
        ),
    ]
