# Generated by Django 5.2.8 on 2026-01-01 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_fvideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speaker_type', models.CharField(choices=[('keynote', 'Keynote Speaker'), ('invited', 'Invited Speaker')], max_length=10)),
                ('name', models.CharField(max_length=200)),
                ('affiliation', models.CharField(max_length=300)),
                ('photo', models.ImageField(upload_to='speakers/')),
                ('talk_title', models.CharField(blank=True, help_text='For keynote speakers', max_length=500, null=True)),
                ('abstract', models.TextField(blank=True, help_text='For keynote speakers', null=True)),
                ('session', models.CharField(blank=True, help_text='For invited speakers', max_length=300, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
