# Generated by Django 5.2.8 on 2026-01-01 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_accommodation_fieldvisit_travel_venue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Popup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content_type', models.CharField(choices=[('text', 'Text Message'), ('image', 'Image/Photo')], default='text', help_text='Choose to display text message or image', max_length=10)),
                ('message', models.TextField(blank=True, help_text="Text message to display (only used if Content Type is 'Text')")),
                ('image', models.ImageField(blank=True, help_text="Upload image (only used if Content Type is 'Image')", null=True, upload_to='popups/')),
                ('image_alt_text', models.CharField(blank=True, help_text='Alternative text for image accessibility', max_length=200)),
                ('popup_type', models.CharField(choices=[('announcement', 'Announcement'), ('warning', 'Warning'), ('info', 'Information'), ('promotion', 'Promotion')], default='announcement', help_text='Choose the type of popup', max_length=20)),
                ('button_text', models.CharField(default='Got it!', help_text='Text for the close button', max_length=50)),
                ('link_url', models.URLField(blank=True, help_text='Optional link URL (e.g., registration page)', null=True)),
                ('link_text', models.CharField(blank=True, help_text='Text for the link button', max_length=100)),
                ('show_on_homepage', models.BooleanField(default=True, help_text='Show popup on homepage')),
                ('show_on_all_pages', models.BooleanField(default=False, help_text='Show popup on all pages')),
                ('delay_seconds', models.IntegerField(default=0, help_text='Delay in seconds before showing popup (0 = immediate)')),
                ('show_once_per_session', models.BooleanField(default=True, help_text='Show only once per browser session')),
                ('cookie_days', models.IntegerField(default=1, help_text='Days to remember user closed popup (if show_once_per_session is False)')),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable this popup')),
                ('priority', models.IntegerField(default=0, help_text='Higher number = higher priority')),
                ('start_date', models.DateTimeField(blank=True, help_text='Optional: Start showing from this date', null=True)),
                ('end_date', models.DateTimeField(blank=True, help_text='Optional: Stop showing after this date', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Popup',
                'verbose_name_plural': 'Popups',
                'ordering': ['-priority', '-created_at'],
            },
        ),
    ]
