# Generated by Django 5.2.8 on 2026-01-01 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_popup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='popup',
            options={'ordering': ['-created_at'], 'verbose_name': 'Popup', 'verbose_name_plural': 'Popups'},
        ),
        migrations.RemoveField(
            model_name='popup',
            name='button_text',
        ),
        migrations.RemoveField(
            model_name='popup',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='popup',
            name='cookie_days',
        ),
        migrations.RemoveField(
            model_name='popup',
            name='delay_seconds',
        ),
        migrations.RemoveField(
            model_name='popup',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='popup',
            name='image_alt_text',
        ),
        migrations.RemoveField(
            model_name='popup',
            name='link_text',
        ),
        migrations.RemoveField(
            model_name='popup',
            name='link_url',
        ),
        migrations.RemoveField(
            model_name='popup',
            name='message',
        ),
        migrations.RemoveField(
            model_name='popup',
            name='popup_type',
        ),
        migrations.RemoveField(
            model_name='popup',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='popup',
            name='show_on_all_pages',
        ),
        migrations.RemoveField(
            model_name='popup',
            name='show_on_homepage',
        ),
        migrations.RemoveField(
            model_name='popup',
            name='show_once_per_session',
        ),
        migrations.RemoveField(
            model_name='popup',
            name='start_date',
        ),
        migrations.AddField(
            model_name='popup',
            name='description',
            field=models.TextField(default='No description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='popup',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='popup_images/'),
        ),
        migrations.AlterField(
            model_name='popup',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Only one popup will be shown at a time'),
        ),
    ]
